/* Generated by Together */

package org.ensembl.datamodel.impl;

import org.ensembl.datamodel.DnaDnaAlignment;
import org.ensembl.datamodel.Location;
import org.ensembl.driver.CoreDriver;

/**
 * Implementation of DnaDnaAlignment
 * @author Frans Verhoef
 */
public class DnaDnaAlignmentImpl extends BaseFeaturePairImpl implements DnaDnaAlignment {

  /**
   * Used by the (de)serialization system to determine if the data 
   * in a serialized instance is compatible with this class.
   *
   * It's presence allows for compatible serialized objects to be loaded when
   * the class is compatible with the serialized instance, even if:
   *
   * <ul>
   * <li> the compiler used to compile the "serializing" version of the class
   * differs from the one used to compile the "deserialising" version of the
   * class.</li>
   *
   * <li> the methods of the class changes but the attributes remain the same.</li>
   * </ul>
   *
   * Maintainers must change this value if and only if the new version of
   * this class is not compatible with old versions. e.g. attributes
   * change. See Sun docs for <a
   * href="http://java.sun.com/j2se/1.4.2/docs/guide/serialization/">
   * details. </a>
   *
   */
  private static final long serialVersionUID = 1L;


  public DnaDnaAlignmentImpl() {
    super();
  }

  public DnaDnaAlignmentImpl( long internalID, Location location, Location hitLocation ) {
    super( internalID, location, hitLocation );
  }

  public DnaDnaAlignmentImpl( CoreDriver driver) {
    super( driver );
  }

}
