/*                    BioJava development code
 *
 * This code may be freely distributed and modified under the
 * terms of the GNU Lesser General Public Licence.  This should
 * be distributed with the code.  If you do not have a copy,
 * see:
 *
 *      http://www.gnu.org/copyleft/lesser.html
 *
 * Copyright for this code is held jointly by the individual
 * authors.  These should be listed in @author doc comments.
 *
 * For more information on the BioJava project and its aims,
 * or to join the biojava-l mailing list, visit the home page
 * at:
 *
 *      http://www.biojava.org/
 *
 */

package org.biojava.bio.seq.genomic;

/**
 * This is a feature that sits within an RNA sequence, and represents a region
 * that is translated into protein. All sequence before this is 5'utr, and all
 * sequence after is 3'utr.
 *
 * @author Matthew Pocock
 */
public interface TranslatedRegion {
  public Sequence getTranslation();
  
  /**
   * Template class for parameterizing the creation of a new Translated Region.
   *
   * @author Matthew Pocock
   */
  public class Template extends Feature.Template {
    /**
     * The associated translation. If this is null, then the translation should
     * be auto-generated by translating the region within this feature. If it is
     * supplied, then firstly the alphabet should be checked to ensure that it
     * is PROTEIN, and secondly, basic checks should be made about its length.
     */
    public Sequence translation;
  }
}
